// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_wPZ58-FewvYG2O0irk4bO9WmRNUANs',
    appId: '1:768235612864:web:b21bc6e76a2948dc9e1b25',
    messagingSenderId: '768235612864',
    projectId: 'e-commerce-app-6350a',
    authDomain: 'e-commerce-app-6350a.firebaseapp.com',
    storageBucket: 'e-commerce-app-6350a.firebasestorage.app',
    measurementId: 'G-9H00MR9BLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0F3wLY2vgprDiKbglR77xLC7C6U484Do',
    appId: '1:768235612864:android:7a044ea4c9dd38d89e1b25',
    messagingSenderId: '768235612864',
    projectId: 'e-commerce-app-6350a',
    storageBucket: 'e-commerce-app-6350a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxqrUGS85W48Z_misMmMovIxVqwRMme8',
    appId: '1:768235612864:ios:2fc7f7a130fab7089e1b25',
    messagingSenderId: '768235612864',
    projectId: 'e-commerce-app-6350a',
    storageBucket: 'e-commerce-app-6350a.firebasestorage.app',
    iosClientId: '768235612864-4s1u86g7g982rvvi3cpqobjnudp1t2ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
